apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: vault
  namespace: filhodanuvem-services
spec:
  interval: 1m
  chart:
    spec:
      chart: vault
      version: 0.18.0
      sourceRef: 
        kind: HelmRepository
        name: hashicorp
        namespace: flux-system
      interval: 1m
  values:
    server:
      logLevel: "debug"
      dev:
        enabled: true
      # dataStorage:
      #   enabled: false