apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: grafana
  namespace: filhodanuvem-services
spec:
  interval: 1m
  chart:
    spec:
      chart: grafana
      version: 6.19.0
      sourceRef: 
        kind: HelmRepository
        name: grafana
        namespace: flux-system
      interval: 1m
  values:
    adminUser: admin
    adminPassword: admin
    datasources:
       datasources.yaml:
         apiVersion: 1
         datasources:
         - name: Prometheus
           type: prometheus
           url: http://prometheus-server
           access: proxy
           isDefault: true
    sidecar:
      dashboards:
        enabled: true
    dashboardProviders:
      dashboardproviders.yaml:
        apiVersion: 1
        providers:
        - name: 'default'
          orgId: 1
          folder: ''
          type: file
          disableDeletion: false
          editable: true
          options:
            path: /var/lib/grafana/dashboards/default
    dashboardsConfigMaps:
      default: dashboard-config
    
