apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: nack
  namespace: filhodanuvem-services
spec:
  interval: 1m
  chart:
    spec:
      chart: nack
      version: 0.6.0
      sourceRef: 
        kind: HelmRepository
        name: nack
        namespace: flux-system
      interval: 1m
  values:
    jetstream:
      enabled: true
    nats: 
      url: "nats://nats-0.nats.filhodanuvem-services.svc.cluster.local:4222"
