apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: nack
  namespace: filhodanuvem-services
spec:
  interval: 1m
  chart:
    spec:
      chart: nack
      version: 0.9.2
      sourceRef: 
        kind: HelmRepository
        name: nack
        namespace: flux-system
      interval: 1m
  values:
    
