apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: nats
  namespace: filhodanuvem-services
spec:
  interval: 1m
  chart:
    spec:
      chart: nats
      version: 0.9.2
      sourceRef: 
        kind: HelmRepository
        name: nats
        namespace: flux-system
      interval: 1m
  values:
    nats: 
      jetstream:
        enabled: true

        memStorage:
          enabled: false
          size: 2Gi

        fileStorage:
          enabled: true
          size: 1Gi
          storageDirectory: /data/
          storageClassName: local
    reloader:
      enabled: false
