apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: nats
  namespace: default
spec:
  chart:
    git: git@github.com/nats-io/k8s.git
    path: helm/charts/
    ref: master
  values:
    nats:
