apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: nats
  namespace: default
spec:
  chart:
    spec:
      chart: nats
      sourceRef: HelmRepository
      name: nats
  values:
    nats:
