apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: nats
  namespace: default
spec:
  chart:
    git: github.com:nats-io/k8s.git
    path: helm/charts/nats
    ref: master
  values:
    nats:
