apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: nats
  namespace: default
spec:
  interval: 1m
  chart:
    spec:
      chart: nats
      sourceRef: 
        kind: HelmRepository
        name: nats
        namespace: flux-system
      interval: 1m
  values:
    nats:
