apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: payment-producer
  namespace: filhodanuvem-services
spec:
  interval: 1m
  chart:
    spec:
      chart: producer
      version: 0.1.0
      sourceRef: 
        kind: HelmRepository
        name: payment-producer
        namespace: filhodanuvem-services
      interval: 1m
  values:
    cilium: 
      enabled: true
    nats:
      url: "nats://nats:4222"
      subject: "payment.orders"
    replicaCount: 1
