apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: elasticsearch
  namespace: filhodanuvem-services
spec:
  interval: 1m
  chart:
    spec:
      chart: stable/elasticsearch
      version: 1.32.5
      sourceRef:
        kind: HelmRepository
        name: elasticsearch
        namespace: flux-system
      interval: 1m
  values:
    provisionDataStore:
      cassandra: false
      elasticsearch: true
      kafka: false
    storage:
      type: elasticsearch
    elasticsearch:
      host: elasticsearch
      