apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: elasticsearch
  namespace: filhodanuvem-services
spec:
  interval: 1m
  chart:
    spec:
      chart: elasticsearch
      version: 1.32.5
      sourceRef:
        kind: HelmRepository
        name: elasticsearch
        namespace: flux-system
      interval: 1m
  values:
    data:
      replicas: 1
    client:
      replicas: 1
    master:
      replicas: 1
    initResources:
      limits:
        cpu: "25m"
        memory: "128Mi"
      requests:
        cpu: "25m"
        memory: "128Mi"
    resources:
      limits:
        cpu: "1"
        memory: "1024Mi"
      requests:
        cpu: "25m"
        memory: "512Mi"