apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: cilium
  namespace: filhodanuvem-services
spec:
  interval: 1m
  chart:
    spec:
      chart: cilium
      version: 1.11.0
      sourceRef: 
        kind: HelmRepository
        name: cilium
        namespace: flux-system
      interval: 1m
  values:
    policyEnforcementMode: "always" 
    cluster:
      name: cilium-cluster
      id: 1
    clustermesh:
      useAPIServer: false
    hubble:
      enabled: true
      relay:
        enabled: true
      ui: 
        enabled: true
    operator:
      replicas: 1
  