apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment-api
  namespace: filhodanuvem-services
  labels:
    app: payment-api 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: payment-api
  template:
    metadata:
      labels:
        app: payment-api
      annotations:
          prometheus.io/scrape: "true"
          prometheus.io/port: "2222"
          prometheus.io/path: /metrics
          vault.hashicorp.com/service: "http://vault:8200"
          vault.hashicorp.com/agent-inject: 'true'
          vault.hashicorp.com/agent-inject-status: 'update'
          vault.hashicorp.com/role: 'app'
          vault.hashicorp.com/agent-inject-secret-userpassword: 'secret/data/user/password'
          vault.hashicorp.com/agent-inject-template-userpassword: |
            {{ with secret "secret/data/user/password" -}}
              export USER_PASSWORD="{{ .Data.data.user_password }}"
            {{- end }}
    spec:
      serviceAccountName: payments
      containers:
      - name: api
        image: cloudson/log-api:latest
        ports:
        - containerPort: 8081
        args:
            ['sh', '-c', 'source /vault/secrets/userpassword && ./main']
