apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment-api
  namespace: filhodanuvem-services
  labels:
    app: payment-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: payment-api
  template:
    metadata:
      labels:
        app: payment-api
    spec:
      containers:
      - name: api
        image: cloudson/log-api:latest
        ports:
        - containerPort: 8081
