apiVersion: v1
kind: Service
metadata:
  name: payment-api
  namespace: filhodanuvem-services
spec:
  selector:
    app: payment-api
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081