apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: prometheus
  namespace: filhodanuvem-services
spec:
  interval: 1m
  chart:
    spec:
      chart: prometheus
      version: 15.0.1
      sourceRef: 
        kind: HelmRepository
        name: prometheus
        namespace: flux-system
      interval: 1m
  values:
