input:
  label: "consumer"
  nats_jetstream:
    urls:
      - nats://nats-0.nats.filhodanuvem-services.svc.cluster.local:4222
    subject: "payment.orders"
    queue: "paymentqueue"
    durable: "paymentstream"
    deliver: all
output:
  label: "posting"
  http_client:
    url: http://api:8081/
    verb: POST
    headers:
      Content-Type: application/json
    rate_limit: ""
    timeout: 5s
    max_in_flight: 1
    batching:
      count: 0
      byte_size: 0
      period: ""
      check: ""