input:
  label: ""
  nats_jetstream:
    urls:
      - nats://nats-0.nats.filhodanuvem-services.svc.cluster.local:4222
    # queue: ""
    subject: "purchases"
    durable: "purchases"
    deliver: last