input:
  label: ""
  nats_jetstream:
    urls:
      - nats://nats-0.nats.filhodanuvem-services.svc.cluster.local:4222
    subject: "payment.orders"
    queue: "paymentqueue"
    durable: "paymentstream"
    deliver: all