input:
  label: "consumer"
  nats_jetstream:
    urls:
      - nats://nats-0.nats.filhodanuvem-services.svc.cluster.local:4222
    subject: "payment.orders"
    queue: "paymentqueue"
    durable: "paymentstream"
    deliver: all
output:
  label: "posting"
  http_client:
    url: http://payment-api:8081/
    verb: POST
    headers:
      Content-Type: application/json
      Traceparent: ${! json("headers.traceparent") }
    rate_limit: ""
    timeout: 5s
    max_in_flight: 1
    batching:
      count: 0
      byte_size: 0
      period: ""
      check: ""
pipeline:
  processors:
    - for_each:
      - log:
          level: INFO
          fields:
            amount: ${! json("amount") }
            headers: ${! json("headers") }
logger:
  prefix: benthos
  level: DEBUG
  format: json
  add_timestamp: true
  static_fields:
    '@service': benthos
tracer:
  jaeger:
    collector_url: "jaeger-collector:14268"
    service_name: consumer-post
    sampler_type: const
    flush_interval: ""