apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: jaeger
  namespace: filhodanuvem-services
spec:
  interval: 1m
  chart:
    spec:
      chart: jaeger
      version: 0.51.5
      sourceRef: 
        kind: HelmRepository
        name: jaeger
        namespace: flux-system
      interval: 1m
  values:
    provisionDataStore:
      cassandra: false
      elasticsearch: true
      kafka: false
    storage:
      type: elasticsearch
    elasticsearch:
      scheme: http
      host: elasticsearch
      port: 9200
      user: elastic
      usePassword: false
      