apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: jaeger
  namespace: filhodanuvem-services
spec:
  interval: 1m
  chart:
    spec:
      chart: jaeger
      version: 0.51.5
      sourceRef: 
        kind: HelmRepository
        name: jaeger
        namespace: flux-system
      interval: 1m
  values:
    storage:
      type: elasticsearch
      