apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment-producer
  namespace: filhodanuvem-services
  labels:
    app: payment-producer
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: payment-producer
  template:
    metadata:
      labels:
        app: payment-producer
    spec:
      containers:
        - name: payment-producer
          image: cloudson/producer:latest
          env:
            - name: NATS_URL
              value: {{ .Values.nats.url }}
            - name: NATS_SUBJECT
              value: {{ .Values.nats.subject }}
