name: 'Terraform'

on:
  push:
    branches: 
    - master

jobs:
  Build:
    name: "Docker build"
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: "Build"
      run: |
        docker login --username cloudson --password ${{ secrets.DOCKERHUB_TOKEN }}
        cd 3-continuous-deployment/flux/services/producer
        make
        cd - 
        cd 4-telemetry/flux/services/api
        make 
  Helm:
    name: "Helm release"
    runs-on: ubuntu-latest
    needs: Build
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Find current version
      run: |
        curl \
          -H "Accept: application/vnd.github.v3+json" \
          https://api.github.com/repos/${GITHUB_REPOSITORY}/releases/latest > ./latest_release
        export HELM_VERSION=$(cat ./latest_release | sed 's/producer-//1' | jq -r '.tag_name')
        echo "HELM_VERSION=${HELM_VERSION:-0.0.0}" >> $GITHUB_ENV
        echo "Helm version: ${HELM_VERSION}"
    - name: Increment Semantic Version
      id: bump_helm_version
      uses: christian-draeger/increment-semantic-version@1.0.2
      with:
        current-version: "${{ env.HELM_VERSION }}"
        version-fragment: "feature"
    - uses: azure/setup-helm@v1
    - name: "Helm"
      run: |
        cd 3-continuous-deployment/helm/producer
        sed 's/latest/${{ secrets.GITHUB_SHA }}/g' values.yaml > values.yaml
        cd - 
        helm package --version "${{ steps.bump_helm_version.outputs.next-version }}" 3-continuous-deployment/helm/producer
    - uses: ncipollo/release-action@v1
      with:
        artifacts: "producer-${{ steps.bump_helm_version.outputs.next-version }}.tgz"
        token: ${{ secrets.GITHUB_TOKEN }}  
        draft: true
        name: "producer-${{ steps.bump_helm_version.outputs.next-version }}"  
        tag: "producer-${{ steps.bump_helm_version.outputs.next-version }}"
        commit: "${{ env.GITHUB_SHA }}"    
