name: 'Terraform'

on:
  push:
    branches: 
    - master

jobs:
  Build:
    name: "Docker build"
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: "Build"
      run: |
        docker login --username cloudson --password ${{ secrets.DOCKERHUB_TOKEN }}
        cd 3-continuous-deployment/flux/services/producer
        make
        cd - 
        cd 4-telemetry/flux/services/api
        make 
  Helm:
    name: "Helm release"
    runs-on: ubuntu-latest
    needs: Build
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Find current version
      run: |
        curl \
          -H "Accept: application/vnd.github.v3+json" \
          https://api.github.com/repos/${GITHUB_REPOSITORY}/releases/latest > ./latest_release
        export HELM_VERSION=$(cat ./latest_release | sed 's/producer-//1' | jq -r '.tag_name')
        echo "HELM_VERSION=${HELM_VERSION}" >> $GITHUB_ENV
        echo "Helm version: ${HELM_VERSION}"
    - name: Increment Semantic Version
      id: bump_helm_version
      uses: christian-draeger/increment-semantic-version@1.0.2
      with:
        current-version: "${{ env.HELM_VERSION }}"
        version-fragment: "feature"
    - uses: azure/setup-helm@v1
    - name: "Helm"
      run: | 
        helm package --version "${{ steps.bump_helm_version.outputs.next-version }}" 3-continuous-deployment/helm/producer
        curl -X POST \
          -H "Authorization: token $CLOUD_GITHUB_TOKEN" \
          -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/repos/${GITHUB_REPOSITORY}/releases \
          -d '{"tag_name": "producer-${{ steps.bump_helm_version.outputs.next-version }}"}'
    
    
    # curl \
    #   -X POST \
    #   -H "Accept: application/vnd.github.v3+json" \
    #   https://uploads.github.com/repos/octocat/hello-world/releases/42/assets
    # - name: "Helm"  
    #   run: |
    #     cd 3-continuous-deployment/helm/producer
    #     sed 's/latest/${{ secrets.GITHUB_SHA }}/g' values.yaml > values.yaml
    #     sed 's/template_appVersion/${{ steps.bump_version.outputs.next-version }}/g' Chart.yaml > Chart.yaml
    #     sed 's/template_appVersion/${{ steps.bump_version.outputs.next-version }}/g' ../index.yaml > ../index.yaml
    # - uses: helm/chart-releaser-action@v1.1.0
    #   with:
    #     charts_dir: 3-continuous-deployment/helm/producer
    #   env:
    #     CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"    
