name: 'Terraform'

on:
  push:
    branches: 
    - master

jobs:
  Build:
    name: "Docker build"
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: "Build"
      run: |
        docker login --username cloudson --password ${{ secrets.DOCKERHUB_TOKEN }}
        cd 3-continuous-deployment/flux/services/producer
        make
        cd - 
        cd 4-telemetry/flux/services/api
        make 
  Helm:
    name: "Helm release"
    runs-on: ubuntu-latest
    needs: Build
    steps:
    - uses: actions/checkout@v2
    - name: Find current version
      run: |
        curl \
          -H "Accept: application/vnd.github.v3+json" \
          https://api.github.com/repos/${GITHUB_REPOSITORY}/releases/latest > ./latest_release
        export HELM_VERSION=$(cat ./latest_release | sed 's/producer-//1' | jq -r '.tag_name')
        echo "HELM_VERSION=${HELM_VERSION}" >> $GITHUB_ENV
        echo "Helm version: ${HELM_VERSION}"
    - name: Increment Semantic Version
      uses: christian-draeger/increment-semantic-version@1.0.2
      with:
        current-version: "${HELM_VERSION}"
        version-fragment: "feature"
    - name: "Helm"  
      run: |
        cd 3-continuous-deployment/helm/producer
        sed 's/latest/${{ secrets.GITHUB_SHA }}/g' values.yaml > values.yaml
        sed 's/template_appVersion/${{ steps.bump_version.outputs.next-version }}/g' Chart.yaml > Chart.yaml
    - uses: helm/chart-releaser-action@v1.1.0
      with:
        charts_dir: 3-continuous-deployment/helm
      env:
        CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"    
