name: 'Helm'

on:
  push:
    branches:
    - master

jobs:
  Test:
    name: "Test"
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: helm/kind-action@v1.2.0
    - uses: azure/setup-helm@v1
    - name: "Helm"
      run: |
        kubectl create namespace filhodanuvem-services
        helm install producer ./3-continuous-deployment/helm/producer
        helm test producer